In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
base = pd.read_csv("netflix_titles.csv")
base.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [3]:
base.shape

(8807, 12)

In [4]:
rating = base["rating"]
type(base["rating"])

pandas.core.series.Series

In [5]:
type_title = base[["type", "title"]]
type_title

         type                  title
0       Movie   Dick Johnson Is Dead
1     TV Show          Blood & Water
2     TV Show              Ganglands
3     TV Show  Jailbirds New Orleans
4     TV Show           Kota Factory
...       ...                    ...
8802    Movie                 Zodiac
8803  TV Show            Zombie Dumb
8804    Movie             Zombieland
8805    Movie                   Zoom
8806    Movie                 Zubaan

[8807 rows x 2 columns]

In [161]:
filter_ = base.query("release_year >= 2021")[["release_year","type", "title"]]
filter_

      release_year     type                      title
1             2021  TV Show              Blood & Water
2             2021  TV Show                  Ganglands
3             2021  TV Show      Jailbirds New Orleans
4             2021  TV Show               Kota Factory
5             2021  TV Show              Midnight Mass
...            ...      ...                        ...
1468          2021    Movie  What Happened to Mr. Cha?
1551          2021  TV Show                      Hilda
1696          2021  TV Show               Polly Pocket
2920          2021  TV Show              Love Is Blind
8437          2021  TV Show     The Netflix Afterparty

[592 rows x 3 columns]

In [166]:
filter_3 = filter_.iloc[1:5]
filter_3

   release_year     type                  title
2          2021  TV Show              Ganglands
3          2021  TV Show  Jailbirds New Orleans
4          2021  TV Show           Kota Factory
5          2021  TV Show          Midnight Mass

## Revisão ativa

Estado: a revisar. As células acima preservam o estudo anterior; saídas antigas não comprovam uma execução limpa. Consulte o [registro de dificuldades](../00_guia/progresso.md).

- Pergunta ou conceito deste exercício: _preencher_.
- Por que escolhi esse procedimento: _preencher_.
- Como conferi a saída: _preencher_.
- Conclusão e limitação: _preencher_.

## Prática independente

Refaça uma parte com a solução fechada e altere os dados ou a pergunta. Registre o que mudou e onde precisou consultar documentação. Ao terminar, reinicie o kernel, execute tudo e atualize o progresso.