In [1]:
import numpy as np
import pandas as pd

In [2]:
array = np.array(np.random.randint(1, 1000, 5))

print(array)

def amplitude(lista) -> float:
    print(f"Amplitude: {max(lista) - min(lista)}")

amplitude(array)

[ 99 113 691 429 858]
Amplitude: 759

In [3]:
# Carrega o arquivo para dataframe Pandas
# german_credit_data.csv
dados = pd.read_csv("Credit.csv", encoding="utf-8", quotechar="'")

#Formato
dados.shape
#Linhas, Colunas

(1000, 21)

In [4]:
# Resumo estatistico
dados.describe()

,duration,credit_amount,installment_commitment,residence_since,age,existing_credits,num_dependents
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,20.903000,3271.258000,2.973000,2.845000,35.546000,1.407000,1.155000
std,12.058814,2822.736876,1.118715,1.103718,11.375469,0.577654,0.362086
min,4.000000,250.000000,1.000000,1.000000,19.000000,1.000000,1.000000
25%,12.000000,1365.500000,2.000000,2.000000,27.000000,1.000000,1.000000
50%,18.000000,2319.500000,3.000000,3.000000,33.000000,1.000000,1.000000
75%,24.000000,3972.250000,4.000000,4.000000,42.000000,2.000000,1.000000
max,72.000000,18424.000000,4.000000,4.000000,75.000000,4.000000,2.000000

In [ ]:
# |Primeiros registros
dados.head() # Sem parametro mostra 5

<bound method NDFrame.head of     checking_status  duration                  credit_history  \
0                <0         6  critical/other existing credit
1          0<=X<200        48                   existing paid
2       no checking        12  critical/other existing credit
3                <0        42                   existing paid
4                <0        24              delayed previously
..              ...       ...                             ...
995     no checking        12                   existing paid
996              <0        30                   existing paid
997     no checking        12                   existing paid
998              <0        45                   existing paid
999        0<=X<200        45  critical/other existing credit

                 purpose  credit_amount    savings_status  employment  \
0               radio/tv           1169  no known savings         >=7
1               radio/tv           5951              <100      1<=X<4
2              education           2096              <100      4<=X<7
3    furniture/equipment           7882              <100      4<=X<7
4                new car           4870              <100      1<=X<4
..                   ...            ...               ...         ...
995  furniture/equipment           1736              <100      4<=X<7
996             used car           3857              <100      1<=X<4
997             radio/tv            804              <100         >=7
998             radio/tv           1845              <100      1<=X<4
999             used car           4576        100<=X<500  unemployed

     installment_commitment     personal_status other_parties  ...  \
0                         4         male single          none  ...
1                         2  female div/dep/mar          none  ...
2                         2         male single          none  ...
3                         2         male single     guarantor  ...
4                         3         male single          none  ...
..                      ...                 ...           ...  ...
995                       3  female div/dep/mar          none  ...
996                       4        male div/sep          none  ...
997                       4         male single          none  ...
998                       4         male single          none  ...
999                       3         male single          none  ...

     property_magnitude age  other_payment_plans   housing existing_credits  \
0           real estate  67                 none       own                2
1           real estate  22                 none       own                1
2           real estate  49                 none       own                1
3        life insurance  45                 none  for free                1
4     no known property  53                 none  for free                2
..                  ...  ..                  ...       ...              ...
995         real estate  31                 none       own                1
996      life insurance  40                 none       own                1
997                 car  38                 none       own                1
998   no known property  23                 none  for free                1
999                 car  27                 none       own                1

                           job num_dependents  own_telephone foreign_worker  \
0                      skilled              1            yes            yes
1                      skilled              1           none            yes
2           unskilled resident              2           none            yes
3                      skilled              2           none            yes
4                      skilled              2           none            yes
..                         ...            ...            ...            ...
995         unskilled resident              1           none            yes
996  high qualif/self emp/mgmt              1            yes            yes
997                    skilled              1           none            yes
998                    skilled              1            yes            yes
999                    skilled              1           none            yes

    class
0    good
1     bad
2    good
3    good
4     bad
..    ...
995  good
996  good
997  good
998   bad
999  good

[1000 rows x 21 columns]>

In [6]:
# Ultimos registros
dados.tail(2)

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
998,<0,45,existing paid,radio/tv,1845,<100,1<=X<4,4,male single,none,...,no known property,23,none,for free,1,skilled,1,yes,yes,bad
999,0<=X<200,45,critical/other existing credit,used car,4576,100<=X<500,unemployed,3,male single,none,...,car,27,none,own,1,skilled,1,none,yes,good

In [215]:
# Filtos por nome da coluna
dados[["duration"]]

     duration
0           6
1          48
2          12
3          42
4          24
..        ...
995        12
996        30
997        12
998        45
999        45

[1000 rows x 1 columns]

In [216]:
# Filtrar linhas por indice
dados.loc[1:3]

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
1,0<=X<200,48,existing paid,radio/tv,5951,<100,1<=X<4,2,female div/dep/mar,none,...,real estate,22,none,own,1,skilled,1,none,yes,bad
2,no checking,12,critical/other existing credit,education,2096,<100,4<=X<7,2,male single,none,...,real estate,49,none,own,1,unskilled resident,2,none,yes,good
3,<0,42,existing paid,furniture/equipment,7882,<100,4<=X<7,2,male single,guarantor,...,life insurance,45,none,for free,1,skilled,2,none,yes,good

In [217]:
dados.loc[[1,3]]

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
1,0<=X<200,48,existing paid,radio/tv,5951,<100,1<=X<4,2,female div/dep/mar,none,...,real estate,22,none,own,1,skilled,1,none,yes,bad
3,<0,42,existing paid,furniture/equipment,7882,<100,4<=X<7,2,male single,guarantor,...,life insurance,45,none,for free,1,skilled,2,none,yes,good

In [218]:
# Filtro

dados.loc[dados["credit_amount"] > 18000]

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
915,0<=X<200,48,no credits/all paid,other,18424,<100,1<=X<4,1,female div/dep/mar,none,...,life insurance,32,bank,own,1,high qualif/self emp/mgmt,1,yes,no,bad

In [219]:
creditos = dados.loc[dados['credit_amount'] > 18000]
print(creditos)

    checking_status  duration       credit_history purpose  credit_amount  \
915        0<=X<200        48  no credits/all paid   other          18424

    savings_status employment  installment_commitment     personal_status  \
915           <100     1<=X<4                       1  female div/dep/mar

    other_parties  ...  property_magnitude age  other_payment_plans housing  \
915          none  ...      life insurance  32                 bank     own

    existing_credits                        job num_dependents  own_telephone  \
915                1  high qualif/self emp/mgmt              1            yes

    foreign_worker class
915             no   bad

[1 rows x 21 columns]

In [220]:
creditos3 = dados[['checking_status', 'duration']].loc[dados['credit_amount'] > 18000]
print(creditos)

    checking_status  duration       credit_history purpose  credit_amount  \
915        0<=X<200        48  no credits/all paid   other          18424

    savings_status employment  installment_commitment     personal_status  \
915           <100     1<=X<4                       1  female div/dep/mar

    other_parties  ...  property_magnitude age  other_payment_plans housing  \
915          none  ...      life insurance  32                 bank     own

    existing_credits                        job num_dependents  own_telephone  \
915                1  high qualif/self emp/mgmt              1            yes

    foreign_worker class
915             no   bad

[1 rows x 21 columns]

In [223]:
s1 = pd.Series([2, 4, 6, 3, 88, 99])
print(s1)

0     2
1     4
2     6
3     3
4    88
5    99
dtype: int64

In [ ]:
s2 = dados['purpose']
print(s)
type(s2)

pandas.core.series.Series

In [225]:
s3 = dados[['purpose']]
type(s3)

pandas.core.frame.DataFrame

In [227]:
dados.rename(columns={"duration": "duração", "purpose": "proposito"}, inplace=True)

In [228]:
dados.head(1)

,checking_status,duração,credit_history,proposito,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,<0,6,critical/other existing credit,radio/tv,1169,no known savings,>=7,4,male single,none,...,real estate,67,none,own,2,skilled,1,yes,yes,good

In [229]:
dados.isnull()

,checking_status,duração,credit_history,proposito,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [231]:
dados.isnull().sum()

checking_status           0
duração                   0
credit_history            0
proposito                 0
credit_amount             0
savings_status            0
employment                0
installment_commitment    0
personal_status           0
other_parties             0
residence_since           0
property_magnitude        0
age                       0
other_payment_plans       0
housing                   0
existing_credits          0
job                       0
num_dependents            0
own_telephone             0
foreign_worker            0
class                     0
dtype: int64

In [232]:
dados.iloc[0:3, 0:5]

,checking_status,duração,credit_history,proposito,credit_amount
0,<0,6,critical/other existing credit,radio/tv,1169
1,0<=X<200,48,existing paid,radio/tv,5951
2,no checking,12,critical/other existing credit,education,2096

In [233]:
dados.iloc[[0,1,2,3,7], 0:5]

,checking_status,duração,credit_history,proposito,credit_amount
0,<0,6,critical/other existing credit,radio/tv,1169
1,0<=X<200,48,existing paid,radio/tv,5951
2,no checking,12,critical/other existing credit,education,2096
3,<0,42,existing paid,furniture/equipment,7882
7,0<=X<200,36,existing paid,used car,6948

## Revisão ativa

Estado: a revisar. As células acima preservam o estudo anterior; saídas antigas não comprovam uma execução limpa. Consulte o [registro de dificuldades](../00_guia/progresso.md).

- Pergunta ou conceito deste exercício: _preencher_.
- Por que escolhi esse procedimento: _preencher_.
- Como conferi a saída: _preencher_.
- Conclusão e limitação: _preencher_.

## Prática independente

Refaça uma parte com a solução fechada e altere os dados ou a pergunta. Registre o que mudou e onde precisou consultar documentação. Ao terminar, reinicie o kernel, execute tudo e atualize o progresso.